// registry/solid/ui/badge.tsx
import { type JSX, splitProps } from "solid-js";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/registry/solid/lib/utils";

const badgeVariants = cva(
  "inline-flex items-center justify-center gap-2 rounded-sm border px-3 py-[3px] font-mono text-[10px] uppercase tracking-[0.32em] whitespace-nowrap transition-[color,background,border,box-shadow] shadow-[inset_0_0_0_1px_rgba(255,255,255,0.04)] [&>svg]:size-3 [&>svg]:pointer-events-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
  {
    variants: {
      variant: {
        default: "border-foreground/60 bg-foreground/10 text-foreground hover:bg-foreground/15",
        secondary: "border-border/60 bg-muted/40 text-foreground/70 hover:bg-muted/50",
        destructive:
          "border-destructive/60 bg-destructive/10 text-destructive hover:bg-destructive/15 focus-visible:ring-destructive/30",
        outline: "border-border/60 text-muted-foreground hover:bg-muted/30",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

type BadgeProps = JSX.HTMLAttributes<HTMLSpanElement> & VariantProps<typeof badgeVariants>;

function Badge(props: BadgeProps) {
  const [local, rest] = splitProps(props, ["class", "variant"]);

  return (
    <span
      data-slot="badge"
      class={cn(badgeVariants({ variant: local.variant }), local.class)}
      {...rest}
    />
  );
}

export { Badge, badgeVariants };

// apps/demo/src/demos/react/badge.tsx
import { Badge } from "@/registry/react/ui/badge";

export default function BadgeDemo() {
  return (
    <div className="flex flex-col gap-6">
      <div className="space-y-2">
        <h2 className="text-xs uppercase tracking-[0.3em] text-muted-foreground">Variants</h2>
        <div className="flex flex-wrap items-center gap-3">
          <Badge>Default</Badge>
          <Badge variant="secondary">Secondary</Badge>
          <Badge variant="outline">Outline</Badge>
          <Badge variant="destructive">Destructive</Badge>
        </div>
      </div>

      <div className="space-y-2">
        <h2 className="text-xs uppercase tracking-[0.3em] text-muted-foreground">Inline Usage</h2>
        <div className="flex flex-wrap items-center gap-2 rounded-lg border px-4 py-3 text-sm">
          <span className="font-mono text-xs uppercase tracking-[0.28em]">Deployment</span>
          <Badge variant="outline">Preview</Badge>
          <Badge>Active</Badge>
          <Badge variant="secondary">Synced</Badge>
        </div>
      </div>
    </div>
  );
}
