// apps/demo/src/demos/solid/input-otp.tsx
import { createSignal } from "solid-js";

import { Button } from "@/registry/solid/ui/button";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/registry/solid/ui/input-otp";

export default function InputOTPDemo() {
  const [value, setValue] = createSignal("");

  return (
    <div class="flex flex-col items-center justify-center gap-6">
      <InputOTP value={value()} onValueChange={setValue} maxLength={6}>
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>

      <div class="text-sm text-muted-foreground font-mono tracking-[0.3em] uppercase">
        Value: <span class="text-foreground">{value() || "------"}</span>
      </div>

      <div class="flex items-center gap-3">
        <Button variant="muted" onClick={() => setValue("")} disabled={!value()}>
          Clear
        </Button>
      </div>
    </div>
  );
}

// apps/demo/src/demos/react/input-otp.tsx
import { useState } from "react";

import { Button } from "@/registry/react/ui/button";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/registry/react/ui/input-otp";

export default function InputOTPDemo() {
  const [value, setValue] = useState("");

  return (
    <div className="flex flex-col items-center justify-center gap-6">
      <InputOTP value={value} onChange={setValue} maxLength={6}>
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>

      <div className="text-sm text-muted-foreground font-mono tracking-[0.3em] uppercase">
        Value: <span className="text-foreground">{value || "------"}</span>
      </div>

      <div className="flex items-center gap-3">
        <Button variant="muted" onClick={() => setValue("")} disabled={!value}>
          Clear
        </Button>
      </div>
    </div>
  );
}
