// apps/demo/src/demos/solid/sidebar.tsx
import { createSignal } from "solid-js"
import { CheckCircle2, LayoutDashboard, Shield, Zap } from "lucide-solid"

import { Badge } from "@/registry/solid/ui/badge"
import { Button } from "@/registry/solid/ui/button"
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarInset,
  SidebarMenu,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarProvider,
  SidebarRail,
  SidebarSeparator,
  SidebarTrigger,
} from "@/registry/solid/ui/sidebar"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/registry/solid/ui/card"

export default function SidebarDemo() {
  const [active, setActive] = createSignal("overview")

  return (
    <div class="overflow-hidden rounded-none border border-border/70">
      <SidebarProvider defaultOpen class="relative flex min-h-[360px]">
        <Sidebar class="bg-muted/20">
          <SidebarHeader class="gap-4">
            <SidebarInput placeholder="Search services" />
          </SidebarHeader>
          <SidebarContent>
            <SidebarGroup>
              <SidebarGroupLabel>Overview</SidebarGroupLabel>
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton
                    onClick={() => setActive("overview")}
                    isActive={active() === "overview"}
                  >
                    <LayoutDashboard class="size-4" />
                    Control plane
                  </SidebarMenuButton>
                </SidebarMenuItem>
                <SidebarMenuItem>
                  <SidebarMenuButton
                    onClick={() => setActive("security")}
                    isActive={active() === "security"}
                  >
                    <Shield class="size-4" />
                    Security
                    <SidebarMenuBadge>2</SidebarMenuBadge>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarGroup>

            <SidebarSeparator />

            <SidebarGroup>
              <SidebarGroupLabel>Automation</SidebarGroupLabel>
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton
                    onClick={() => setActive("workflows")}
                    isActive={active() === "workflows"}
                  >
                    <Zap class="size-4" />
                    Workflows
                  </SidebarMenuButton>
                </SidebarMenuItem>
                <SidebarMenuItem>
                  <SidebarMenuSkeleton />
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarGroup>
          </SidebarContent>
          <SidebarFooter>
            <Button variant="ghost" class="w-full justify-start gap-3">
              <CheckCircle2 class="size-4" />
              Launch checks
            </Button>
          </SidebarFooter>
          <SidebarRail />
        </Sidebar>
        <SidebarInset class="flex-1 bg-background/40 p-6">
          <div class="flex items-center justify-between">
            <SidebarTrigger />
            <Badge variant="outline" class="tracking-[0.32em] uppercase">
              {active()}
            </Badge>
          </div>
          <Card class="mt-6 border-border/70">
            <CardHeader>
              <CardTitle class="font-mono text-xs uppercase tracking-[0.32em] text-muted-foreground">
                {active() === "overview" ? "Control plane" : active() === "security" ? "Security posture" : "Workflow automations"}
              </CardTitle>
              <CardDescription>
                Content area demonstrates how the inset pairs with the sidebar.
              </CardDescription>
            </CardHeader>
            <CardContent class="text-sm text-muted-foreground">
              This panel inherits the frosted backdrop while the sidebar keeps
              its glass rail and uppercase markers.
            </CardContent>
          </Card>
        </SidebarInset>
      </SidebarProvider>
    </div>
  )
}

// apps/demo/src/demos/react/sidebar.tsx
import { useState } from "react"
import { CheckCircle2, LayoutDashboard, Shield, Zap } from "lucide-react"

import { Badge } from "@/registry/react/ui/badge"
import { Button } from "@/registry/react/ui/button"
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarInset,
  SidebarMenu,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarProvider,
  SidebarRail,
  SidebarSeparator,
  SidebarTrigger,
} from "@/registry/react/ui/sidebar"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/registry/react/ui/card"

export default function SidebarDemo() {
  const [active, setActive] = useState("overview")

  return (
    <div className="overflow-hidden rounded-none border border-border/70">
      <SidebarProvider defaultOpen className="relative flex min-h-[360px]">
        <Sidebar className="bg-muted/20">
          <SidebarHeader className="gap-4">
            <SidebarInput placeholder="Search services" />
          </SidebarHeader>
          <SidebarContent>
            <SidebarGroup>
              <SidebarGroupLabel>Overview</SidebarGroupLabel>
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton
                    onClick={() => setActive("overview")}
                    isActive={active === "overview"}
                  >
                    <LayoutDashboard className="size-4" />
                    Control plane
                  </SidebarMenuButton>
                </SidebarMenuItem>
                <SidebarMenuItem>
                  <SidebarMenuButton
                    onClick={() => setActive("security")}
                    isActive={active === "security"}
                  >
                    <Shield className="size-4" />
                    Security
                    <SidebarMenuBadge>2</SidebarMenuBadge>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarGroup>

            <SidebarSeparator />

            <SidebarGroup>
              <SidebarGroupLabel>Automation</SidebarGroupLabel>
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton
                    onClick={() => setActive("workflows")}
                    isActive={active === "workflows"}
                  >
                    <Zap className="size-4" />
                    Workflows
                  </SidebarMenuButton>
                </SidebarMenuItem>
                <SidebarMenuItem>
                  <SidebarMenuSkeleton />
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarGroup>
          </SidebarContent>
          <SidebarFooter>
            <Button variant="ghost" className="w-full justify-start gap-3">
              <CheckCircle2 className="size-4" />
              Launch checks
            </Button>
          </SidebarFooter>
          <SidebarRail />
        </Sidebar>
        <SidebarInset className="flex-1 bg-background/40 p-6">
          <div className="flex items-center justify-between">
            <SidebarTrigger />
            <Badge variant="outline" className="tracking-[0.32em] uppercase">
              {active}
            </Badge>
          </div>
          <Card className="mt-6 border-border/70">
            <CardHeader>
              <CardTitle className="font-mono text-xs uppercase tracking-[0.32em] text-muted-foreground">
                {active === "overview" ? "Control plane" : active === "security" ? "Security posture" : "Workflow automations"}
              </CardTitle>
              <CardDescription>
                Content area demonstrates how the inset pairs with the sidebar.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">
              This panel inherits the frosted backdrop while the sidebar keeps
              its glass rail and uppercase markers.
            </CardContent>
          </Card>
        </SidebarInset>
      </SidebarProvider>
    </div>
  )
}
