// registry/react/ui/accordion.tsx
"use client";

import * as React from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { ChevronDownIcon } from "lucide-react";

import { cn } from "@/registry/react/lib/utils";

const containerStyles = "divide-y divide-border/60 text-muted-foreground/80 dark:text-foreground";

function Accordion({ className, ...props }: React.ComponentProps<typeof AccordionPrimitive.Root>) {
  return (
    <AccordionPrimitive.Root
      data-slot="accordion"
      className={cn(containerStyles, className)}
      {...props}
    />
  );
}

function AccordionItem({
  className,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Item>) {
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      className={cn(
        "group relative overflow-hidden transition-colors",
        "before:absolute before:left-0 before:top-1.5 before:bottom-1.5 before:w-px before:origin-bottom before:scale-y-0 before:bg-primary/50 before:transition-transform before:duration-200 before:content-['']",
        "data-[state=open]:before:scale-y-100",
        className,
      )}
      {...props}
    />
  );
}

function AccordionTrigger({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Trigger>) {
  return (
    <AccordionPrimitive.Header className="relative">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        className={cn(
          "flex w-full items-center justify-between gap-5 px-4 py-4 text-left",
          "font-mono text-[10px] uppercase tracking-[0.32em] text-muted-foreground/80 dark:text-muted-foreground",
          "outline-none transition-colors",
          "hover:text-foreground",
          "focus-visible:ring-2 focus-visible:ring-ring/35 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
          "data-[state=open]:text-foreground data-[state=open]:tracking-[0.34em]",
          "disabled:pointer-events-none disabled:opacity-40",
          "[&>[data-slot=accordion-chevron]]:transition-transform [&[data-state=open]>[data-slot=accordion-chevron]]:rotate-180",
          className,
        )}
        {...props}
      >
        <span className="flex-1 leading-snug tracking-[0.3em]">{children}</span>
        <span
          data-slot="accordion-chevron"
          className="inline-flex size-5 items-center justify-center text-muted-foreground/60 transition-transform group-hover:text-foreground"
        >
          <ChevronDownIcon className="size-3" />
        </span>
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  );
}

function AccordionContent({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Content>) {
  return (
    <AccordionPrimitive.Content
      data-slot="accordion-content"
      className="overflow-hidden text-sm text-foreground/80 data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
      {...props}
    >
      <div
        className={cn(
          "px-4 pb-4 pt-1.5 leading-relaxed text-muted-foreground/90 dark:text-foreground/80",
          className,
        )}
      >
        {children}
      </div>
    </AccordionPrimitive.Content>
  );
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };

// registry/solid/ui/accordion.tsx
import { splitProps, type ComponentProps } from "solid-js";
import * as AccordionPrimitive from "@kobalte/core/accordion";
import { ChevronDownIcon } from "lucide-solid";
import { cn } from "@/registry/solid/lib/utils";

const containerStyles = "divide-y divide-border/60 text-muted-foreground/80 dark:text-foreground";

function Accordion(props: ComponentProps<typeof AccordionPrimitive.Root>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <AccordionPrimitive.Root
      data-slot="accordion"
      class={cn(containerStyles, local.class)}
      {...rest}
    >
      {local.children}
    </AccordionPrimitive.Root>
  );
}

function AccordionItem(props: ComponentProps<typeof AccordionPrimitive.Item>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      class={cn(
        "group relative overflow-hidden transition-colors",
        "before:absolute before:left-0 before:top-1.5 before:bottom-1.5 before:w-px before:origin-bottom before:scale-y-0 before:bg-primary/50 before:transition-transform before:duration-200 before:content-['']",
        "data-[expanded]:before:scale-y-100",
        local.class,
      )}
      {...rest}
    >
      {local.children}
    </AccordionPrimitive.Item>
  );
}

function AccordionTrigger(props: ComponentProps<typeof AccordionPrimitive.Trigger>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <AccordionPrimitive.Header class="relative">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        class={cn(
          "flex w-full items-center justify-between gap-5 px-4 py-4 text-left",
          "font-mono text-[10px] uppercase tracking-[0.32em] text-muted-foreground/80 dark:text-muted-foreground",
          "outline-none transition-colors",
          "hover:text-foreground",
          "focus-visible:ring-2 focus-visible:ring-ring/35 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
          "data-[expanded]:text-foreground data-[expanded]:tracking-[0.34em]",
          "disabled:pointer-events-none disabled:opacity-40",
          "[&>[data-slot=accordion-chevron]]:transition-transform [&[data-expanded]>[data-slot=accordion-chevron]]:rotate-180",
          local.class,
        )}
        {...rest}
      >
        <span class="flex-1 leading-snug tracking-[0.3em]">{local.children}</span>
        <span
          data-slot="accordion-chevron"
          class="inline-flex size-5 items-center justify-center text-muted-foreground/60 transition-transform group-hover:text-foreground"
        >
          <ChevronDownIcon class="size-3" />
        </span>
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  );
}

function AccordionContent(props: ComponentProps<typeof AccordionPrimitive.Content>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <AccordionPrimitive.Content
      data-slot="accordion-content"
      class="overflow-hidden text-sm text-foreground/80 data-[closed]:animate-accordion-up data-[expanded]:animate-accordion-down"
      {...rest}
    >
      <div
        class={cn(
          "px-4 pb-4 pt-1.5 leading-relaxed text-muted-foreground/90 dark:text-foreground/80",
          local.class,
        )}
      >
        {local.children}
      </div>
    </AccordionPrimitive.Content>
  );
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };
