// apps/demo/src/demos/react/card.tsx
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/registry/react/ui/card";
import { Button } from "@/registry/react/ui/button";
import { Badge } from "@/registry/react/ui/badge";
import { Separator } from "@/registry/react/ui/separator";

export default function CardDemo() {
  return (
    <Card className="divide-y divide-border">
      <CardHeader>
        <div>
          <CardTitle className="text-sm font-medium text-card-foreground/80 dark:text-card-foreground/70">
            Usage
          </CardTitle>
          <CardDescription className="mt-2 text-base text-card-foreground">
            Daily Active Sessions
          </CardDescription>
        </div>
        <CardAction>
          <Badge variant="outline">Live</Badge>
        </CardAction>
      </CardHeader>
      <CardContent>
        <div className="flex items-end justify-between">
          <div className="space-y-1">
            <span className="text-4xl font-semibold tracking-tight text-card-foreground">
              3,482
            </span>
            <p className="text-sm text-muted-foreground">+12.4% vs previous cycle</p>
          </div>
          <Button size="sm">View report</Button>
        </div>
      </CardContent>
      <CardFooter>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <span className="font-medium text-card-foreground/70">Next update</span>
          <Separator orientation="vertical" className="mx-2 h-4" />
          <span className="text-muted-foreground">In 15 minutes</span>
        </div>
      </CardFooter>
    </Card>
  );
}

// registry/solid/ui/card.tsx
import { type JSX, splitProps } from "solid-js";

import { cn } from "@/registry/solid/lib/utils";

function Card(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="card"
      class={cn(
        "flex flex-col rounded-none border border-border bg-card text-card-foreground",
        local.class,
      )}
      {...rest}
    />
  );
}

function CardHeader(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="card-header"
      class={cn(
        "grid auto-rows-min grid-rows-[auto_auto] items-start gap-2 px-6 py-5 has-data-[slot=card-action]:grid-cols-[1fr_auto] border-b border-border text-muted-foreground",
        local.class,
      )}
      {...rest}
    />
  );
}

function CardTitle(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="card-title"
      class={cn("leading-none font-semibold text-card-foreground", local.class)}
      {...rest}
    />
  );
}

function CardDescription(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="card-description"
      class={cn("text-muted-foreground text-sm", local.class)}
      {...rest}
    />
  );
}

function CardAction(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="card-action"
      class={cn("col-start-2 row-span-2 row-start-1 self-start justify-self-end", local.class)}
      {...rest}
    />
  );
}

function CardContent(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return <div data-slot="card-content" class={cn("px-6 py-6", local.class)} {...rest} />;
}

function CardFooter(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="card-footer"
      class={cn(
        "flex items-center justify-between gap-3 border-t border-border px-6 py-4 text-muted-foreground",
        local.class,
      )}
      {...rest}
    />
  );
}

export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent };
