// registry/react/ui/checkbox.tsx
"use client";

import * as React from "react";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { CheckIcon } from "lucide-react";

import { cn } from "@/registry/react/lib/utils";

function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer size-4 shrink-0 border border-border/60 bg-muted/40 text-foreground/80 shadow-[var(--glass-shadow-inset)] transition-[border,background,color,box-shadow] outline-none",
        "focus-visible:border-foreground focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
        "aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive/30 dark:aria-invalid:focus-visible:ring-destructive/40",
        "data-[state=checked]:bg-foreground data-[state=checked]:text-background",
        "disabled:cursor-not-allowed disabled:opacity-40",
        "rounded-none",
        className,
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="flex items-center justify-center text-current transition-none"
      >
        <CheckIcon className="size-3.5" />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  );
}

export { Checkbox };

// registry/solid/ui/checkbox.tsx
import { splitProps, type ComponentProps, type JSX } from "solid-js";
import * as CheckboxPrimitive from "@kobalte/core/checkbox";
import { CheckIcon } from "lucide-solid";

import { useOptionalFormControlProps } from "@/registry/solid/lib/form-control";
import { cn } from "@/registry/solid/lib/utils";

function Checkbox(props: ComponentProps<typeof CheckboxPrimitive.Root>) {
  const [local, rest] = splitProps(props, ["class", "children", "id"]);
  const formControlProps = useOptionalFormControlProps();
  return (
    <CheckboxPrimitive.Root data-slot="checkbox" {...rest}>
      <CheckboxPrimitive.Input
        id={local.id ?? formControlProps?.().id}
        aria-describedby={formControlProps?.()["aria-describedby"]}
        aria-invalid={formControlProps?.()["aria-invalid"]}
      />
      <CheckboxPrimitive.Control
        onClick={(event) => event.preventDefault()}
        class={cn(
          "peer size-4 shrink-0 border border-border/60 bg-muted/40 text-foreground/80 shadow-[var(--glass-shadow-inset)] transition-[border,background,color,box-shadow] outline-none",
          "focus-visible:border-foreground focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
          "aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive/30 dark:aria-invalid:focus-visible:ring-destructive/40",
          "data-[checked]:bg-foreground data-[checked]:text-background",
          "disabled:cursor-not-allowed disabled:opacity-40",
          "rounded-none",
          local.class,
        )}
      >
        <CheckboxPrimitive.Indicator
          data-slot="checkbox-indicator"
          class="flex items-center justify-center text-current transition-none"
        >
          <CheckIcon class="size-3.5" />
        </CheckboxPrimitive.Indicator>
      </CheckboxPrimitive.Control>
      {local.children as JSX.Element}
    </CheckboxPrimitive.Root>
  );
}

export { Checkbox };
