// registry/react/ui/command.tsx
"use client";

import * as React from "react";
import { Command as CommandPrimitive } from "cmdk";
import { SearchIcon } from "lucide-react";

import { cn } from "@/registry/react/lib/utils";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/registry/react/ui/dialog";

function Command({ className, ...props }: React.ComponentProps<typeof CommandPrimitive>) {
  return (
    <CommandPrimitive
      data-slot="command"
      className={cn(
        "flex h-full w-full flex-col overflow-hidden text-foreground backdrop-blur-[10px]",
        "omni-glass-inset-surface",
        className,
      )}
      {...props}
    />
  );
}

function CommandDialog({
  title = "Command Palette",
  description = "Search for a command to run…",
  children,
  className,
  showCloseButton = true,
  ...props
}: React.ComponentProps<typeof Dialog> & {
  title?: string;
  description?: string;
  className?: string;
  showCloseButton?: boolean;
}) {
  return (
    <Dialog {...props}>
      <DialogHeader className="sr-only">
        <DialogTitle>{title}</DialogTitle>
        <DialogDescription>{description}</DialogDescription>
      </DialogHeader>
      <DialogContent
        className={cn(
          "overflow-hidden border border-border/60 bg-muted/30 p-0 text-foreground shadow-[var(--glass-shadow-outline-heavy)] backdrop-blur-[12px]",
          "rounded-none",
          className,
        )}
        showCloseButton={showCloseButton}
      >
        <Command className="border-0 bg-transparent shadow-none backdrop-blur-none">
          {children}
        </Command>
      </DialogContent>
    </Dialog>
  );
}

function CommandInput({
  className,
  "aria-label": ariaLabel,
  placeholder,
  ...props
}: React.ComponentProps<typeof CommandPrimitive.Input>) {
  const inputLabel =
    ariaLabel ?? (typeof placeholder === "string" ? placeholder : "Search commands");

  return (
    <div
      data-slot="command-input-wrapper"
      className="flex h-11 items-center gap-2.5 border-b border-border/60 bg-muted/40 px-3 transition-[border,box-shadow] focus-within:border-foreground focus-within:ring-2 focus-within:ring-ring/40"
    >
      <SearchIcon className="size-4 shrink-0 opacity-50" aria-hidden="true" />
      <CommandPrimitive.Input
        aria-label={inputLabel}
        data-slot="command-input"
        placeholder={placeholder}
        className={cn(
          "flex h-full w-full bg-transparent text-sm text-foreground/90 outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-40",
          className,
        )}
        {...props}
      />
    </div>
  );
}

function CommandList({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.List>) {
  return (
    <CommandPrimitive.List
      data-slot="command-list"
      className={cn("max-h-[320px] scroll-py-1 overflow-x-hidden overflow-y-auto", className)}
      {...props}
    />
  );
}

function CommandEmpty({ ...props }: React.ComponentProps<typeof CommandPrimitive.Empty>) {
  return (
    <CommandPrimitive.Empty
      data-slot="command-empty"
      className="py-6 text-center text-xs text-muted-foreground"
      {...props}
    />
  );
}

function CommandGroup({
  className,
  ...props
}: React.ComponentProps<typeof CommandPrimitive.Group>) {
  return (
    <CommandPrimitive.Group
      data-slot="command-group"
      className={cn(
        "overflow-hidden px-1 py-1 text-foreground [&_[cmdk-group-heading]]:px-3 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground",
        className,
      )}
      {...props}
    />
  );
}

function CommandSeparator({
  className,
  ...props
}: React.ComponentProps<typeof CommandPrimitive.Separator>) {
  return (
    <CommandPrimitive.Separator
      data-slot="command-separator"
      className={cn(
        "pointer-events-none -mx-1 my-1 h-px bg-gradient-to-r from-transparent via-border/70 to-transparent",
        className,
      )}
      {...props}
    />
  );
}

function CommandItem({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.Item>) {
  return (
    <CommandPrimitive.Item
      data-slot="command-item"
      className={cn(
        "relative flex min-h-10 cursor-default select-none items-center gap-2.5 px-3 py-2.5 text-sm leading-normal text-muted-foreground/85 outline-hidden transition-[background,color] [&_*]:leading-normal",
        "data-[selected=true]:bg-foreground data-[selected=true]:text-background",
        "data-[selected=true]:[&_[data-slot=command-shortcut]]:text-background/70",
        "data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-40",
        "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        "rounded-none",
        className,
      )}
      {...props}
    />
  );
}

function CommandShortcut({ className, ...props }: React.ComponentProps<"span">) {
  return (
    <span
      data-slot="command-shortcut"
      className={cn(
        "ml-auto font-mono text-xs text-muted-foreground/70 transition-colors",
        className,
      )}
      {...props}
    />
  );
}

export {
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandShortcut,
  CommandSeparator,
};

// registry/solid/ui/command.tsx
import type { Component, ComponentProps, ParentProps, VoidProps } from "solid-js";
import { splitProps } from "solid-js";

import type { DialogRootProps } from "@kobalte/core/dialog";
import * as CommandPrimitive from "cmdk-solid";
import { SearchIcon } from "lucide-solid";

import { cn } from "@/registry/solid/lib/utils";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/registry/solid/ui/dialog";

const Command: Component<ParentProps<CommandPrimitive.CommandRootProps>> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <CommandPrimitive.CommandRoot
      data-slot="command"
      class={cn(
        "flex h-full w-full flex-col overflow-hidden text-foreground backdrop-blur-[10px]",
        "omni-glass-inset-surface",
        local.class,
      )}
      {...others}
    />
  );
};

const CommandDialog: Component<
  ParentProps<DialogRootProps & { title?: string; description?: string }>
> = (props) => {
  const [local, others] = splitProps(props, ["children", "title", "description"]);
  return (
    <Dialog {...others}>
      <DialogHeader class="sr-only">
        <DialogTitle>{local.title ?? "Command Palette"}</DialogTitle>
        <DialogDescription>{local.description ?? "Search for a command to run…"}</DialogDescription>
      </DialogHeader>
      <DialogContent
        class={cn(
          "overflow-hidden border border-border/60 bg-muted/30 p-0 text-foreground shadow-[var(--glass-shadow-outline-heavy)] backdrop-blur-[12px]",
          "rounded-none",
        )}
      >
        <Command class="border-0 bg-transparent shadow-none backdrop-blur-none">
          {local.children}
        </Command>
      </DialogContent>
    </Dialog>
  );
};

const CommandInput: Component<VoidProps<CommandPrimitive.CommandInputProps>> = (props) => {
  const [local, others] = splitProps(props, ["class", "aria-label", "placeholder"]);
  const inputLabel = () =>
    local["aria-label"] ??
    (typeof local.placeholder === "string" ? local.placeholder : "Search commands");

  return (
    <div
      data-slot="command-input-wrapper"
      class="flex h-11 items-center gap-2.5 border-b border-border/60 bg-muted/40 px-3 transition-[border,box-shadow] focus-within:border-foreground focus-within:ring-2 focus-within:ring-ring/40"
    >
      <SearchIcon class="size-4 shrink-0 opacity-50" aria-hidden="true" />
      <CommandPrimitive.CommandInput
        aria-label={inputLabel()}
        data-slot="command-input"
        placeholder={local.placeholder}
        class={cn(
          "flex h-full w-full bg-transparent text-sm text-foreground/90 outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-40",
          local.class,
        )}
        {...others}
      />
    </div>
  );
};

const CommandList: Component<ParentProps<CommandPrimitive.CommandListProps>> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <CommandPrimitive.CommandList
      data-slot="command-list"
      class={cn("max-h-[320px] scroll-py-1 overflow-x-hidden overflow-y-auto", local.class)}
      {...others}
    />
  );
};

const CommandEmpty: Component<ParentProps<CommandPrimitive.CommandEmptyProps>> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <CommandPrimitive.CommandEmpty
      data-slot="command-empty"
      class={cn("py-6 text-center text-xs text-muted-foreground", local.class)}
      {...others}
    />
  );
};

const CommandGroup: Component<ParentProps<CommandPrimitive.CommandGroupProps>> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <CommandPrimitive.CommandGroup
      data-slot="command-group"
      class={cn(
        "overflow-hidden px-1 py-1 text-foreground [&_[cmdk-group-heading]]:px-3 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground",
        local.class,
      )}
      {...others}
    />
  );
};

const CommandSeparator: Component<VoidProps<CommandPrimitive.CommandSeparatorProps>> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <CommandPrimitive.CommandSeparator
      data-slot="command-separator"
      class={cn(
        "pointer-events-none -mx-1 my-1 h-px bg-gradient-to-r from-transparent via-border/70 to-transparent",
        local.class,
      )}
      {...others}
    />
  );
};

const CommandItem: Component<ParentProps<CommandPrimitive.CommandItemProps>> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <CommandPrimitive.CommandItem
      data-slot="command-item"
      cmdk-item=""
      class={cn(
        "relative flex min-h-10 cursor-default select-none items-center gap-2.5 px-3 py-2.5 text-sm leading-normal text-muted-foreground/85 outline-hidden transition-[background,color] [&_*]:leading-normal",
        "data-[selected=true]:bg-foreground data-[selected=true]:text-background",
        "data-[selected=true]:[&_[data-slot=command-shortcut]]:text-background/70",
        "data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-40",
        "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        "rounded-none",
        local.class,
      )}
      {...others}
    />
  );
};

const CommandShortcut: Component<ComponentProps<"span">> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <span
      data-slot="command-shortcut"
      class={cn(
        "ml-auto font-mono text-xs text-muted-foreground/70 transition-colors",
        local.class,
      )}
      {...others}
    />
  );
};

export {
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandShortcut,
  CommandSeparator,
};
