// registry/new-york/ui/data-table.tsx
"use client"

import * as React from "react"
import {
  type ColumnDef,
  type ColumnFiltersState,
  type SortingState,
  type Table as TableInstance,
  type VisibilityState,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
} from "@tanstack/react-table"
import {
  ArrowDownIcon,
  ArrowUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  SlidersHorizontalIcon,
} from "lucide-react"

import { cn } from "@/registry/new-york/lib/utils"
import { Button } from "@/registry/new-york/ui/button"
import { Input } from "@/registry/new-york/ui/input"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/registry/new-york/ui/select"
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/registry/new-york/ui/dropdown-menu"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/registry/new-york/ui/table"

type DataTableProps<TData, TValue> = {
  columns: ColumnDef<TData, TValue>[]
  data: TData[]
  className?: string
  searchKey?: string
  searchPlaceholder?: string
  toolbar?: (table: TableInstance<TData>) => React.ReactNode
  emptyMessage?: React.ReactNode
  initialPageSize?: number
  pageSizeOptions?: number[]
  footer?: React.ReactNode
  viewOptions?: boolean
}

type DataTableColumnMeta = {
  headerLabel?: string
}

const defaultPageSizeOptions = [10, 20, 30, 50]

function DataTable<TData, TValue>({
  columns,
  data,
  className,
  searchKey,
  searchPlaceholder = "Filter results...",
  toolbar,
  emptyMessage = "No records found.",
  initialPageSize = 10,
  pageSizeOptions = defaultPageSizeOptions,
  footer,
  viewOptions = true,
}: DataTableProps<TData, TValue>) {
  const [sorting, setSorting] = React.useState<SortingState>([])
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>([])
  const [columnVisibility, setColumnVisibility] = React.useState<VisibilityState>({})
  const [rowSelection, setRowSelection] = React.useState({})
  const [searchValue, setSearchValue] = React.useState("")

  const table = useReactTable({
    data,
    columns,
    state: {
      sorting,
      columnFilters,
      columnVisibility,
      rowSelection,
    },
    initialState: {
      pagination: {
        pageSize: initialPageSize,
      },
    },
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  })

  React.useEffect(() => {
    if (!searchKey) return
    const column = table.getColumn(searchKey as string)
    column?.setFilterValue(searchValue)
  }, [table, searchKey, searchValue])

  const isFiltered = Boolean(searchValue) || columnFilters.length > 0

  return (
    <div
      data-slot="data-table"
      className={cn("flex flex-col gap-4", className)}
    >
      <div className="flex flex-col gap-3 border border-border/60 bg-muted/40 px-4 py-3 text-[10px] font-mono uppercase tracking-[0.28em] text-muted-foreground/80 shadow-[var(--glass-shadow-outline)] backdrop-blur-[4px] sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-1 flex-wrap items-center gap-2">
          {toolbar?.(table)}
          {isFiltered ? (
            <Button
              variant="ghost"
              size="sm"
              className="h-8 border border-transparent px-3 py-1 tracking-[0.28em] text-muted-foreground/70 hover:border-border/60 hover:bg-foreground/10 hover:text-foreground"
              onClick={() => {
                setSearchValue("")
                table.resetColumnFilters()
              }}
            >
              Reset
            </Button>
          ) : null}
          <span className="hidden items-center gap-1 text-[9px] tracking-[0.32em] text-muted-foreground/60 sm:inline-flex">
            {table.getFilteredSelectedRowModel().rows.length} selected • {table.getFilteredRowModel().rows.length} total
          </span>
        </div>
        <div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center sm:gap-3">
          {searchKey ? (
            <Input
              value={searchValue}
              onChange={(event) => setSearchValue(event.target.value)}
              placeholder={searchPlaceholder}
              className="h-9 w-full min-w-[220px] border-border/60 bg-background/20 text-[11px] font-mono uppercase tracking-[0.28em] text-foreground/90 sm:w-56"
            />
          ) : null}
          {viewOptions ? <DataTableViewOptions table={table} /> : null}
        </div>
      </div>
      <div className="overflow-hidden border border-border/60 bg-background/10 shadow-[var(--glass-shadow-outline-subtle)] backdrop-blur-[2px]">
        <Table className="min-w-full text-left">
          <TableHeader className="bg-muted/40">
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow
                key={headerGroup.id}
                className="border-border/40 uppercase"
              >
                {headerGroup.headers.map((header) => {
                  if (header.isPlaceholder) {
                    return <TableHead key={header.id} />
                  }

                  const canSort = header.column.getCanSort()
                  const sortDirection = header.column.getIsSorted()

                  return (
                    <TableHead
                      key={header.id}
                      className={cn(
                        "h-12 px-3 text-[10px] font-mono uppercase tracking-[0.32em] text-muted-foreground/80",
                        "[&[data-sort=desc]]:text-foreground [&[data-sort=asc]]:text-foreground"
                      )}
                      data-sort={sortDirection ? String(sortDirection) : undefined}
                    >
                      {canSort ? (
                        <button
                          type="button"
                          onClick={header.column.getToggleSortingHandler()}
                          className="group flex w-full items-center gap-2 text-left transition-colors hover:text-foreground"
                        >
                          <span className="truncate">
                            {flexRender(header.column.columnDef.header, header.getContext())}
                          </span>
                          <span className="flex items-center">
                            {sortDirection === "asc" ? (
                              <ArrowUpIcon className="size-3.5" />
                            ) : sortDirection === "desc" ? (
                              <ArrowDownIcon className="size-3.5" />
                            ) : (
                              <ChevronsUpDownIcon className="size-3.5 opacity-40 group-hover:opacity-70" />
                            )}
                          </span>
                        </button>
                      ) : (
                        flexRender(header.column.columnDef.header, header.getContext())
                      )}
                    </TableHead>
                  )
                })}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows.length ? (
              table.getRowModel().rows.map((row) => (
                <TableRow
                  key={row.id}
                  data-state={row.getIsSelected() ? "selected" : undefined}
                  className="border-border/40 text-sm text-foreground/85 transition-colors hover:bg-muted/30"
                >
                  {row.getVisibleCells().map((cell) => (
                    <TableCell
                      key={cell.id}
                      className="px-3 py-3 text-sm font-mono tracking-[0.08em] text-foreground/80"
                    >
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : (
              <TableRow className="border-border/40">
                <TableCell
                  colSpan={columns.length}
                  className="h-24 px-4 text-center text-sm text-muted-foreground"
                >
                  {emptyMessage}
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
      {footer}
      <DataTablePagination table={table} pageSizeOptions={pageSizeOptions} />
    </div>
  )
}

type DataTableViewOptionsProps<TData> = {
  table: TableInstance<TData>
}

function DataTableViewOptions<TData>({ table }: DataTableViewOptionsProps<TData>) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-9 gap-2 border border-border/60 bg-muted/40 px-3 font-mono uppercase tracking-[0.28em] text-muted-foreground/80 hover:bg-foreground/10 hover:text-foreground"
        >
          <SlidersHorizontalIcon className="size-3.5" />
          View
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        align="end"
        className="min-w-[12rem] border-border/60 bg-muted/60 text-foreground shadow-[var(--glass-shadow-outline)]"
      >
        <DropdownMenuCheckboxItem
          className="pointer-events-none opacity-70"
          checked
        >
          Columns
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem className="pointer-events-none opacity-40" checked>
          —
        </DropdownMenuCheckboxItem>
        {table
          .getAllLeafColumns()
          .filter((column) => column.getCanHide())
          .map((column) => (
            <DropdownMenuCheckboxItem
              key={column.id}
              checked={column.getIsVisible()}
              onCheckedChange={(value) => column.toggleVisibility(Boolean(value))}
              className="font-mono text-[11px] uppercase tracking-[0.28em] text-muted-foreground/80 data-[state=checked]:text-foreground"
            >
              {(column.columnDef.meta as DataTableColumnMeta | undefined)?.headerLabel || column.id}
            </DropdownMenuCheckboxItem>
          ))}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

type DataTablePaginationProps<TData> = {
  table: TableInstance<TData>
  pageSizeOptions?: number[]
}

function DataTablePagination<TData>({
  table,
  pageSizeOptions = defaultPageSizeOptions,
}: DataTablePaginationProps<TData>) {
  const pageSize = table.getState().pagination.pageSize
  const pageCount = table.getPageCount()
  const pageIndex = table.getState().pagination.pageIndex
  const pageStart = pageIndex * pageSize + 1
  const pageEnd = Math.min(pageStart + pageSize - 1, table.getFilteredRowModel().rows.length)

  return (
    <div className="flex flex-col gap-3 border border-border/60 bg-muted/40 px-4 py-3 text-[10px] font-mono uppercase tracking-[0.28em] text-muted-foreground/80 shadow-[var(--glass-shadow-outline)] backdrop-blur-[4px] sm:flex-row sm:items-center sm:justify-between">
      <div className="flex flex-wrap items-center gap-2">
        <span>
          Showing {table.getFilteredRowModel().rows.length ? `${pageStart}–${pageEnd}` : 0} of {" "}
          {table.getFilteredRowModel().rows.length} rows
        </span>
      </div>
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-2">
          <span>Rows</span>
          <Select
            value={String(pageSize)}
            onValueChange={(value) => table.setPageSize(Number(value))}
          >
            <SelectTrigger className="h-8 min-w-[4.5rem] border-border/60 bg-background/20 text-[11px] font-mono uppercase tracking-[0.28em] text-foreground/85">
              <SelectValue />
            </SelectTrigger>
            <SelectContent align="end" className="bg-muted/60">
              <SelectGroup>
                {pageSizeOptions.map((option) => (
                  <SelectItem key={option} value={String(option)}>
                    {option}
                  </SelectItem>
                ))}
              </SelectGroup>
            </SelectContent>
          </Select>
        </div>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="h-8 w-8 border border-border/60 bg-background/20 p-0 text-foreground/80 transition hover:bg-foreground/10 hover:text-foreground"
            onClick={() => table.previousPage()}
            disabled={!table.getCanPreviousPage()}
          >
            <ChevronLeftIcon className="size-3.5" />
            <span className="sr-only">Previous</span>
          </Button>
          <span className="text-[9px] text-muted-foreground/70">
            {pageIndex + 1} / {pageCount || 1}
          </span>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="h-8 w-8 border border-border/60 bg-background/20 p-0 text-foreground/80 transition hover:bg-foreground/10 hover:text-foreground"
            onClick={() => table.nextPage()}
            disabled={!table.getCanNextPage()}
          >
            <ChevronRightIcon className="size-3.5" />
            <span className="sr-only">Next</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

export { DataTable, DataTablePagination, DataTableViewOptions }

// registry/solid/ui/data-table.tsx
import {
  splitProps,
  createSignal,
  createEffect,
  For,
  Show,
  type JSX,
} from "solid-js"
import {
  createSolidTable,
  flexRender,
  getCoreRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  getFilteredRowModel,
  type ColumnDef,
  type ColumnFiltersState,
  type SortingState,
  type VisibilityState,
  type RowSelectionState,
  type Table as TableInstance,
} from "@tanstack/solid-table"
import {
  ArrowDownIcon,
  ArrowUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  SlidersHorizontalIcon,
} from "lucide-solid"

import { cn } from "@/registry/solid/lib/utils"
import { Button } from "@/registry/solid/ui/button"
import { Input } from "@/registry/solid/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/registry/solid/ui/select"
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/registry/solid/ui/dropdown-menu"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/registry/solid/ui/table"

type DataTableColumnMeta = {
  headerLabel?: string
}

type DataTableProps<TData, TValue> = {
  columns: ColumnDef<TData, TValue>[]
  data: TData[]
  class?: string
  searchKey?: string
  searchPlaceholder?: string
  toolbar?: (table: TableInstance<TData>) => JSX.Element
  emptyMessage?: JSX.Element
  initialPageSize?: number
  pageSizeOptions?: number[]
  footer?: JSX.Element
  viewOptions?: boolean
}

const defaultPageSizeOptions = [10, 20, 30, 50]

function DataTable<TData, TValue>(props: DataTableProps<TData, TValue>) {
  const [local] = splitProps(props, [
    "columns",
    "data",
    "class",
    "searchKey",
    "searchPlaceholder",
    "toolbar",
    "emptyMessage",
    "initialPageSize",
    "pageSizeOptions",
    "footer",
    "viewOptions",
  ])

  const [sorting, setSorting] = createSignal<SortingState>([])
  const [columnFilters, setColumnFilters] = createSignal<ColumnFiltersState>([])
  const [columnVisibility, setColumnVisibility] = createSignal<VisibilityState>({})
  const [rowSelection, setRowSelection] = createSignal<RowSelectionState>({})
  const [searchValue, setSearchValue] = createSignal("")

  const table = createSolidTable({
    get data() {
      return local.data
    },
    get columns() {
      return local.columns
    },
    state: {
      get sorting() {
        return sorting()
      },
      get columnFilters() {
        return columnFilters()
      },
      get columnVisibility() {
        return columnVisibility()
      },
      get rowSelection() {
        return rowSelection()
      },
    },
    initialState: {
      pagination: {
        pageSize: local.initialPageSize ?? 10,
      },
    },
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  })

  createEffect(() => {
    if (!local.searchKey) return
    const column = table.getColumn(local.searchKey)
    column?.setFilterValue(searchValue())
  })

  const isFiltered = () => Boolean(searchValue()) || columnFilters().length > 0
  const showViewOptions = () => local.viewOptions !== false

  return (
    <div
      data-slot="data-table"
      class={cn("flex flex-col gap-4", local.class)}
    >
      <div class="flex flex-col gap-3 border border-border/60 bg-muted/40 px-4 py-3 text-[10px] font-mono uppercase tracking-[0.28em] text-muted-foreground/80 shadow-[var(--glass-shadow-outline)] backdrop-blur-[4px] sm:flex-row sm:items-center sm:justify-between">
        <div class="flex flex-1 flex-wrap items-center gap-2">
          {local.toolbar?.(table)}
          <Show when={isFiltered()}>
            <Button
              variant="ghost"
              size="sm"
              class="h-8 border border-transparent px-3 py-1 tracking-[0.28em] text-muted-foreground/70 hover:border-border/60 hover:bg-foreground/10 hover:text-foreground"
              onClick={() => {
                setSearchValue("")
                table.resetColumnFilters()
              }}
            >
              Reset
            </Button>
          </Show>
          <span class="hidden items-center gap-1 text-[9px] tracking-[0.32em] text-muted-foreground/60 sm:inline-flex">
            {table.getFilteredSelectedRowModel().rows.length} selected • {table.getFilteredRowModel().rows.length} total
          </span>
        </div>
        <div class="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center sm:gap-3">
          <Show when={local.searchKey}>
            <Input
              value={searchValue()}
              onInput={(e) => setSearchValue(e.currentTarget.value)}
              placeholder={local.searchPlaceholder ?? "Filter results..."}
              class="h-9 w-full min-w-[220px] border-border/60 bg-background/20 text-[11px] font-mono uppercase tracking-[0.28em] text-foreground/90 sm:w-56"
            />
          </Show>
          <Show when={showViewOptions()}>
            <DataTableViewOptions table={table} />
          </Show>
        </div>
      </div>
      <div class="overflow-hidden border border-border/60 bg-background/10 shadow-[var(--glass-shadow-outline-subtle)] backdrop-blur-[2px]">
        <Table class="min-w-full text-left">
          <TableHeader class="bg-muted/40">
            <For each={table.getHeaderGroups()}>
              {(headerGroup) => (
                <TableRow class="border-border/40 uppercase">
                  <For each={headerGroup.headers}>
                    {(header) => {
                      if (header.isPlaceholder) {
                        return <TableHead />
                      }

                      const canSort = header.column.getCanSort()
                      const sortDirection = () => header.column.getIsSorted()

                      return (
                        <TableHead
                          class={cn(
                            "h-12 px-3 text-[10px] font-mono uppercase tracking-[0.32em] text-muted-foreground/80",
                            "[&[data-sort=desc]]:text-foreground [&[data-sort=asc]]:text-foreground"
                          )}
                          data-sort={sortDirection() ? String(sortDirection()) : undefined}
                        >
                          <Show
                            when={canSort}
                            fallback={flexRender(header.column.columnDef.header, header.getContext())}
                          >
                            <button
                              type="button"
                              onClick={header.column.getToggleSortingHandler()}
                              class="group flex w-full items-center gap-2 text-left transition-colors hover:text-foreground"
                            >
                              <span class="truncate">
                                {flexRender(header.column.columnDef.header, header.getContext())}
                              </span>
                              <span class="flex items-center">
                                <Show when={sortDirection() === "asc"}>
                                  <ArrowUpIcon class="size-3.5" />
                                </Show>
                                <Show when={sortDirection() === "desc"}>
                                  <ArrowDownIcon class="size-3.5" />
                                </Show>
                                <Show when={!sortDirection()}>
                                  <ChevronsUpDownIcon class="size-3.5 opacity-40 group-hover:opacity-70" />
                                </Show>
                              </span>
                            </button>
                          </Show>
                        </TableHead>
                      )
                    }}
                  </For>
                </TableRow>
              )}
            </For>
          </TableHeader>
          <TableBody>
            <Show
              when={table.getRowModel().rows.length > 0}
              fallback={
                <TableRow class="border-border/40">
                  <TableCell
                    colSpan={local.columns.length}
                    class="h-24 px-4 text-center text-sm text-muted-foreground"
                  >
                    {local.emptyMessage ?? "No records found."}
                  </TableCell>
                </TableRow>
              }
            >
              <For each={table.getRowModel().rows}>
                {(row) => (
                  <TableRow
                    data-state={row.getIsSelected() ? "selected" : undefined}
                    class="border-border/40 text-sm text-foreground/85 transition-colors hover:bg-muted/30"
                  >
                    <For each={row.getVisibleCells()}>
                      {(cell) => (
                        <TableCell class="px-3 py-3 text-sm font-mono tracking-[0.08em] text-foreground/80">
                          {flexRender(cell.column.columnDef.cell, cell.getContext())}
                        </TableCell>
                      )}
                    </For>
                  </TableRow>
                )}
              </For>
            </Show>
          </TableBody>
        </Table>
      </div>
      {local.footer}
      <DataTablePagination
        table={table}
        pageSizeOptions={local.pageSizeOptions ?? defaultPageSizeOptions}
      />
    </div>
  )
}

type DataTableViewOptionsProps<TData> = {
  table: TableInstance<TData>
}

function DataTableViewOptions<TData>(props: DataTableViewOptionsProps<TData>) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          class="h-9 gap-2 border border-border/60 bg-muted/40 px-3 font-mono uppercase tracking-[0.28em] text-muted-foreground/80 hover:bg-foreground/10 hover:text-foreground"
        >
          <SlidersHorizontalIcon class="size-3.5" />
          View
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        class="min-w-[12rem] border-border/60 bg-muted/60 text-foreground shadow-[var(--glass-shadow-outline)]"
      >
        <DropdownMenuCheckboxItem
          class="pointer-events-none opacity-70"
          checked
        >
          Columns
        </DropdownMenuCheckboxItem>
        <DropdownMenuCheckboxItem class="pointer-events-none opacity-40" checked>
          —
        </DropdownMenuCheckboxItem>
        <For
          each={props.table
            .getAllLeafColumns()
            .filter((column) => column.getCanHide())}
        >
          {(column) => (
            <DropdownMenuCheckboxItem
              checked={column.getIsVisible()}
              onChange={(value: boolean) => column.toggleVisibility(value)}
              class="font-mono text-[11px] uppercase tracking-[0.28em] text-muted-foreground/80 data-[state=checked]:text-foreground"
            >
              {(column.columnDef.meta as DataTableColumnMeta | undefined)?.headerLabel || column.id}
            </DropdownMenuCheckboxItem>
          )}
        </For>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

type DataTablePaginationProps<TData> = {
  table: TableInstance<TData>
  pageSizeOptions?: number[]
}

function DataTablePagination<TData>(props: DataTablePaginationProps<TData>) {
  const pageSizeOptions = () => props.pageSizeOptions ?? defaultPageSizeOptions
  const pageSize = () => props.table.getState().pagination.pageSize
  const pageCount = () => props.table.getPageCount()
  const pageIndex = () => props.table.getState().pagination.pageIndex
  const pageStart = () => pageIndex() * pageSize() + 1
  const totalRows = () => props.table.getFilteredRowModel().rows.length
  const pageEnd = () => Math.min(pageStart() + pageSize() - 1, totalRows())

  return (
    <div class="flex flex-col gap-3 border border-border/60 bg-muted/40 px-4 py-3 text-[10px] font-mono uppercase tracking-[0.28em] text-muted-foreground/80 shadow-[var(--glass-shadow-outline)] backdrop-blur-[4px] sm:flex-row sm:items-center sm:justify-between">
      <div class="flex flex-wrap items-center gap-2">
        <span>
          Showing {totalRows() ? `${pageStart()}–${pageEnd()}` : 0} of{" "}
          {totalRows()} rows
        </span>
      </div>
      <div class="flex flex-wrap items-center gap-3">
        <div class="flex items-center gap-2">
          <span>Rows</span>
          <Select
            value={String(pageSize())}
            onChange={(val: string) => {
              if (val) props.table.setPageSize(Number(val))
            }}
            options={pageSizeOptions().map(String)}
            itemComponent={(itemProps: any) => (
              <SelectItem item={itemProps.item}>
                {itemProps.item.rawValue}
              </SelectItem>
            )}
          >
            <SelectTrigger class="h-8 min-w-[4.5rem] border-border/60 bg-background/20 text-[11px] font-mono uppercase tracking-[0.28em] text-foreground/85">
              <SelectValue<string>>
                {(state) => state.selectedOption()}
              </SelectValue>
            </SelectTrigger>
            <SelectContent class="bg-muted/60" />
          </Select>
        </div>
        <div class="flex items-center gap-2">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            class="h-8 w-8 border border-border/60 bg-background/20 p-0 text-foreground/80 transition hover:bg-foreground/10 hover:text-foreground"
            onClick={() => props.table.previousPage()}
            disabled={!props.table.getCanPreviousPage()}
          >
            <ChevronLeftIcon class="size-3.5" />
            <span class="sr-only">Previous</span>
          </Button>
          <span class="text-[9px] text-muted-foreground/70">
            {pageIndex() + 1} / {pageCount() || 1}
          </span>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            class="h-8 w-8 border border-border/60 bg-background/20 p-0 text-foreground/80 transition hover:bg-foreground/10 hover:text-foreground"
            onClick={() => props.table.nextPage()}
            disabled={!props.table.getCanNextPage()}
          >
            <ChevronRightIcon class="size-3.5" />
            <span class="sr-only">Next</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

export { DataTable, DataTablePagination, DataTableViewOptions }
