// registry/react/ui/skeleton.tsx
import { cn } from "@/registry/react/lib/utils";

function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      className={cn(
        "animate-pulse rounded-none bg-muted/40 shadow-[var(--glass-shadow-inset)]",
        className,
      )}
      {...props}
    />
  );
}

export { Skeleton };

// registry/solid/ui/skeleton.tsx
import { type JSX, splitProps } from "solid-js";

import { cn } from "@/registry/solid/lib/utils";

function Skeleton(props: JSX.HTMLAttributes<HTMLDivElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="skeleton"
      class={cn(
        "animate-pulse rounded-none bg-muted/40 shadow-[var(--glass-shadow-inset)]",
        local.class,
      )}
      {...rest}
    />
  );
}

export { Skeleton };
