// registry/react/ui/switch.tsx
"use client";

import * as React from "react";
import * as SwitchPrimitive from "@radix-ui/react-switch";

import { cn } from "@/registry/react/lib/utils";

function Switch({ className, ...props }: React.ComponentProps<typeof SwitchPrimitive.Root>) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      className={cn(
        "peer inline-flex h-5 w-9 shrink-0 items-center border border-border/60 bg-muted/50 text-foreground/80 transition-[border,background,color,transform] outline-none disabled:cursor-not-allowed disabled:opacity-40",
        "data-[state=checked]:bg-foreground data-[state=checked]:text-background",
        "focus-visible:border-foreground focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
        "rounded-none",
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(
          "pointer-events-none block size-4 border border-border/60 bg-muted/70 text-current transition-transform",
          "data-[state=unchecked]:translate-x-0",
          "data-[state=checked]:translate-x-[calc(100%-2px)]",
          "rounded-none",
        )}
      />
    </SwitchPrimitive.Root>
  );
}

export { Switch };

// registry/solid/ui/switch.tsx
import { splitProps, type ComponentProps } from "solid-js";
import * as SwitchPrimitive from "@kobalte/core/switch";

import { useOptionalFormControlProps } from "@/registry/solid/lib/form-control";
import { cn } from "@/registry/solid/lib/utils";

function Switch(props: ComponentProps<typeof SwitchPrimitive.Root>) {
  const [local, rest] = splitProps(props, ["class"]);
  const formControlProps = useOptionalFormControlProps();
  return (
    <SwitchPrimitive.Root data-slot="switch" {...rest}>
      <SwitchPrimitive.Input
        id={formControlProps?.().id}
        aria-describedby={formControlProps?.()["aria-describedby"]}
        aria-invalid={formControlProps?.()["aria-invalid"]}
      />
      <SwitchPrimitive.Control
        class={cn(
          "peer inline-flex h-5 w-9 shrink-0 items-center border border-border/60 bg-muted/50 text-foreground/80 transition-[border,background,color,transform] outline-none disabled:cursor-not-allowed disabled:opacity-40",
          "data-[checked]:bg-foreground data-[checked]:text-background",
          "focus-visible:border-foreground focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
          "rounded-none",
          local.class,
        )}
      >
        <SwitchPrimitive.Thumb
          data-slot="switch-thumb"
          class={cn(
            "pointer-events-none block size-4 border border-border/60 bg-muted/70 text-current transition-transform",
            "translate-x-0",
            "data-[checked]:translate-x-[calc(100%-2px)]",
            "rounded-none",
          )}
        />
      </SwitchPrimitive.Control>
    </SwitchPrimitive.Root>
  );
}

export { Switch };
