// apps/demo/src/demos/react/calendar.tsx
import { useMemo, useState } from "react";
import { addDays } from "date-fns";
import type { DateRange } from "react-day-picker";

import { Calendar } from "@/registry/react/ui/calendar";
import { Button } from "@/registry/react/ui/button";

export default function CalendarDemo() {
  const [date, setDate] = useState<Date | undefined>(new Date());
  const [range, setRange] = useState<DateRange | undefined>({
    from: new Date(),
    to: addDays(new Date(), 4),
  });

  const rangeSummary = useMemo(() => {
    if (!range?.from) return "No range selected.";
    if (!range.to) return `Range starts ${range.from.toLocaleDateString()}.`;
    return `${range.from.toLocaleDateString()} -- ${range.to.toLocaleDateString()}`;
  }, [range]);

  return (
    <div className="space-y-8">
      <div className="space-y-3">
        <h3 className="font-mono text-xs uppercase tracking-[0.28em] text-muted-foreground">
          Single date
        </h3>
        <div className="max-w-full overflow-x-auto">
          <Calendar
            mode="single"
            selected={date}
            onSelect={setDate}
            className="rounded-none border border-border/70"
          />
        </div>
        <p className="text-sm text-muted-foreground">
          {date ? `Selected: ${date.toLocaleDateString()}.` : "Select a day."}
        </p>
      </div>

      <div className="space-y-3">
        <h3 className="font-mono text-xs uppercase tracking-[0.28em] text-muted-foreground">
          Date range
        </h3>
        <div className="max-w-full overflow-x-auto">
          <Calendar
            mode="range"
            numberOfMonths={2}
            selected={range}
            onSelect={setRange}
            className="rounded-none border border-border/70"
          />
        </div>
        <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
          <span>{rangeSummary}</span>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setRange(undefined)}
            className="tracking-[0.3em]"
          >
            Reset
          </Button>
        </div>
      </div>
    </div>
  );
}

// apps/demo/src/demos/solid/calendar.tsx
import { createSignal, createMemo } from "solid-js";

import { Calendar } from "@/registry/solid/ui/calendar";
import type { DateRange } from "@/registry/solid/ui/calendar";
import { Button } from "@/registry/solid/ui/button";

function addDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

export default function CalendarDemo() {
  const [date, setDate] = createSignal<Date | undefined>(new Date());
  const [range, setRange] = createSignal<DateRange | undefined>({
    from: new Date(),
    to: addDays(new Date(), 4),
  });

  const rangeSummary = createMemo(() => {
    const r = range();
    if (!r?.from) return "No range selected.";
    if (!r.to) return `Range starts ${r.from.toLocaleDateString()}.`;
    return `${r.from.toLocaleDateString()} -- ${r.to.toLocaleDateString()}`;
  });

  return (
    <div class="space-y-8">
      <div class="space-y-3">
        <h3 class="font-mono text-xs uppercase tracking-[0.28em] text-muted-foreground">
          Single date
        </h3>
        <div class="max-w-full overflow-x-auto">
          <Calendar
            mode="single"
            selected={date()}
            onSelect={setDate}
            class="rounded-none border border-border/70"
          />
        </div>
        <p class="text-sm text-muted-foreground">
          {date() ? `Selected: ${date()!.toLocaleDateString()}.` : "Select a day."}
        </p>
      </div>

      <div class="space-y-3">
        <h3 class="font-mono text-xs uppercase tracking-[0.28em] text-muted-foreground">
          Date range
        </h3>
        <div class="max-w-full overflow-x-auto">
          <Calendar
            mode="range"
            numberOfMonths={2}
            selected={range()}
            onSelect={setRange}
            class="rounded-none border border-border/70"
          />
        </div>
        <div class="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
          <span>{rangeSummary()}</span>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setRange(undefined)}
            class="tracking-[0.3em]"
          >
            Reset
          </Button>
        </div>
      </div>
    </div>
  );
}
