// registry/solid/ui/menubar.tsx
import { splitProps, type ComponentProps, type JSX, type ParentProps } from "solid-js";
import * as MenubarPrimitive from "@kobalte/core/menubar";
import { CheckIcon, ChevronRightIcon, CircleIcon } from "lucide-solid";

import { cn, omniMonoText } from "@/registry/solid/lib/utils";

function Menubar(props: ComponentProps<typeof MenubarPrimitive.Root>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <MenubarPrimitive.Root
      data-slot="menubar"
      class={cn("omni-glass-inset-surface flex h-9 items-center gap-1 px-1", local.class)}
      {...rest}
    />
  );
}

function MenubarMenu(props: ComponentProps<typeof MenubarPrimitive.Menu>) {
  return <MenubarPrimitive.Menu data-slot="menubar-menu" {...props} />;
}

function MenubarGroup(props: ComponentProps<typeof MenubarPrimitive.Group>) {
  return <MenubarPrimitive.Group data-slot="menubar-group" {...props} />;
}

function MenubarPortal(props: ComponentProps<typeof MenubarPrimitive.Portal>) {
  return <MenubarPrimitive.Portal data-slot="menubar-portal" {...props} />;
}

function MenubarRadioGroup(props: ComponentProps<typeof MenubarPrimitive.RadioGroup>) {
  return <MenubarPrimitive.RadioGroup data-slot="menubar-radio-group" {...props} />;
}

function MenubarTrigger(props: ComponentProps<typeof MenubarPrimitive.Trigger>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <MenubarPrimitive.Trigger
      data-slot="menubar-trigger"
      class={cn(
        "flex items-center gap-2 px-2.5 py-1 text-muted-foreground outline-none transition-[color,background]",
        omniMonoText.compact,
        "hover:bg-muted/60 hover:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[expanded]:bg-foreground data-[expanded]:text-background",
        "disabled:pointer-events-none disabled:opacity-50",
        local.class,
      )}
      {...rest}
    />
  );
}

function MenubarContent(props: ComponentProps<typeof MenubarPrimitive.Content>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <MenubarPrimitive.Portal>
      <MenubarPrimitive.Content
        data-slot="menubar-content"
        class={cn(
          "omni-glass-menu-surface z-50 min-w-[12rem] origin-[var(--kb-menu-content-transform-origin)] overflow-hidden p-1",
          "data-[expanded]:animate-in data-[expanded]:zoom-in-95 data-[expanded]:fade-in-0",
          "data-[closed]:animate-out data-[closed]:zoom-out-95 data-[closed]:fade-out-0",
          "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
          local.class,
        )}
        {...rest}
      />
    </MenubarPrimitive.Portal>
  );
}

function MenubarItem(
  props: ComponentProps<typeof MenubarPrimitive.Item> & {
    class?: string;
    inset?: boolean;
    variant?: "default" | "destructive";
  },
) {
  const [local, rest] = splitProps(props, ["class", "inset", "variant"]);
  const variant = () => local.variant ?? "default";
  return (
    <MenubarPrimitive.Item
      data-slot="menubar-item"
      data-inset={local.inset}
      data-variant={variant()}
      class={cn(
        "relative flex min-h-9 cursor-default items-center gap-3 px-3 py-2 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[variant=destructive]:text-destructive data-[variant=destructive]:hover:bg-destructive/10",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        "data-[inset]:pl-8",
        "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5 [&_svg]:text-muted-foreground/70",
        local.class,
      )}
      {...rest}
    />
  );
}

function MenubarCheckboxItem(props: ComponentProps<typeof MenubarPrimitive.CheckboxItem>) {
  const [local, rest] = splitProps(props, ["class", "children", "checked"]);
  return (
    <MenubarPrimitive.CheckboxItem
      data-slot="menubar-checkbox-item"
      class={cn(
        "relative flex min-h-9 cursor-default items-center gap-3 py-2 pl-9 pr-3 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        local.class,
      )}
      checked={local.checked}
      {...rest}
    >
      <span class="pointer-events-none absolute left-3 flex size-3.5 items-center justify-center text-current">
        <MenubarPrimitive.ItemIndicator>
          <CheckIcon class="size-3" />
        </MenubarPrimitive.ItemIndicator>
      </span>
      {local.children}
    </MenubarPrimitive.CheckboxItem>
  );
}

function MenubarRadioItem(props: ComponentProps<typeof MenubarPrimitive.RadioItem>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <MenubarPrimitive.RadioItem
      data-slot="menubar-radio-item"
      class={cn(
        "relative flex min-h-9 cursor-default items-center gap-3 py-2 pl-9 pr-3 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        local.class,
      )}
      {...rest}
    >
      <span class="pointer-events-none absolute left-3 flex size-3.5 items-center justify-center text-current">
        <MenubarPrimitive.ItemIndicator>
          <CircleIcon class="size-2 fill-current" />
        </MenubarPrimitive.ItemIndicator>
      </span>
      {local.children}
    </MenubarPrimitive.RadioItem>
  );
}

function MenubarLabel(
  props: ParentProps<{ class?: string; inset?: boolean } & JSX.HTMLAttributes<HTMLDivElement>>,
) {
  const [local, rest] = splitProps(props, ["class", "inset"]);
  return (
    <div
      data-slot="menubar-label"
      data-inset={local.inset}
      class={cn(
        "px-3 py-1.5 text-muted-foreground/60",
        omniMonoText.compact,
        "data-[inset]:pl-8",
        local.class,
      )}
      {...rest}
    />
  );
}

function MenubarSeparator(props: ComponentProps<typeof MenubarPrimitive.Separator>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <MenubarPrimitive.Separator
      data-slot="menubar-separator"
      class={cn("-mx-1 my-1 h-px bg-border/60", local.class)}
      {...rest}
    />
  );
}

function MenubarShortcut(
  props: ParentProps<{ class?: string } & JSX.HTMLAttributes<HTMLSpanElement>>,
) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <span
      data-slot="menubar-shortcut"
      class={cn("ml-auto text-muted-foreground/60", omniMonoText.base, local.class)}
      {...rest}
    />
  );
}

function MenubarSub(props: ComponentProps<typeof MenubarPrimitive.Sub>) {
  return <MenubarPrimitive.Sub data-slot="menubar-sub" {...props} />;
}

function MenubarSubTrigger(
  props: ComponentProps<typeof MenubarPrimitive.SubTrigger> & {
    inset?: boolean;
  },
) {
  const [local, rest] = splitProps(props, ["class", "inset", "children"]);
  return (
    <MenubarPrimitive.SubTrigger
      data-slot="menubar-sub-trigger"
      data-inset={local.inset}
      class={cn(
        "flex min-h-9 cursor-default items-center gap-3 px-3 py-2 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[expanded]:bg-muted/60 data-[expanded]:text-foreground",
        "data-[inset]:pl-8",
        local.class,
      )}
      {...rest}
    >
      {local.children}
      <ChevronRightIcon class="ml-auto size-3" />
    </MenubarPrimitive.SubTrigger>
  );
}

function MenubarSubContent(props: ComponentProps<typeof MenubarPrimitive.SubContent>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <MenubarPrimitive.SubContent
      data-slot="menubar-sub-content"
      class={cn(
        "omni-glass-menu-surface z-50 min-w-[8rem] origin-[var(--kb-menu-content-transform-origin)] overflow-hidden p-1",
        "data-[expanded]:animate-in data-[expanded]:zoom-in-95 data-[expanded]:fade-in-0",
        "data-[closed]:animate-out data-[closed]:zoom-out-95 data-[closed]:fade-out-0",
        "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
        local.class,
      )}
      {...rest}
    />
  );
}

export {
  Menubar,
  MenubarPortal,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarGroup,
  MenubarSeparator,
  MenubarLabel,
  MenubarItem,
  MenubarShortcut,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
};

// registry/react/ui/menubar.tsx
"use client";

import * as React from "react";
import * as MenubarPrimitive from "@radix-ui/react-menubar";
import { CheckIcon, ChevronRightIcon, CircleIcon } from "lucide-react";

import { cn, omniMonoText } from "@/registry/react/lib/utils";

function Menubar({ className, ...props }: React.ComponentProps<typeof MenubarPrimitive.Root>) {
  return (
    <MenubarPrimitive.Root
      data-slot="menubar"
      className={cn("omni-glass-inset-surface flex h-9 items-center gap-1 px-1", className)}
      {...props}
    />
  );
}

function MenubarMenu({ ...props }: React.ComponentProps<typeof MenubarPrimitive.Menu>) {
  return <MenubarPrimitive.Menu data-slot="menubar-menu" {...props} />;
}

function MenubarGroup({ ...props }: React.ComponentProps<typeof MenubarPrimitive.Group>) {
  return <MenubarPrimitive.Group data-slot="menubar-group" {...props} />;
}

function MenubarPortal({ ...props }: React.ComponentProps<typeof MenubarPrimitive.Portal>) {
  return <MenubarPrimitive.Portal data-slot="menubar-portal" {...props} />;
}

function MenubarRadioGroup({ ...props }: React.ComponentProps<typeof MenubarPrimitive.RadioGroup>) {
  return <MenubarPrimitive.RadioGroup data-slot="menubar-radio-group" {...props} />;
}

function MenubarTrigger({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Trigger>) {
  return (
    <MenubarPrimitive.Trigger
      data-slot="menubar-trigger"
      className={cn(
        "flex items-center gap-2 px-2.5 py-1 text-muted-foreground outline-none transition-[color,background]",
        omniMonoText.compact,
        "hover:bg-muted/60 hover:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[state=open]:bg-foreground data-[state=open]:text-background",
        "disabled:pointer-events-none disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}

function MenubarContent({
  className,
  align = "start",
  alignOffset = -4,
  sideOffset = 8,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Content>) {
  return (
    <MenubarPortal>
      <MenubarPrimitive.Content
        data-slot="menubar-content"
        align={align}
        alignOffset={alignOffset}
        sideOffset={sideOffset}
        className={cn(
          "omni-glass-menu-surface z-50 min-w-[12rem] origin-(--radix-menubar-content-transform-origin) overflow-hidden p-1",
          "data-[state=open]:animate-in data-[state=open]:zoom-in-95 data-[state=open]:fade-in-0",
          "data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=closed]:fade-out-0",
          "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
          className,
        )}
        {...props}
      />
    </MenubarPortal>
  );
}

function MenubarItem({
  className,
  inset,
  variant = "default",
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Item> & {
  inset?: boolean;
  variant?: "default" | "destructive";
}) {
  return (
    <MenubarPrimitive.Item
      data-slot="menubar-item"
      data-inset={inset}
      data-variant={variant}
      className={cn(
        "relative flex min-h-9 cursor-default items-center gap-3 px-3 py-2 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[variant=destructive]:text-destructive data-[variant=destructive]:hover:bg-destructive/10",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        "data-[inset]:pl-8",
        "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5 [&_svg]:text-muted-foreground/70",
        className,
      )}
      {...props}
    />
  );
}

function MenubarCheckboxItem({
  className,
  children,
  checked,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.CheckboxItem>) {
  return (
    <MenubarPrimitive.CheckboxItem
      data-slot="menubar-checkbox-item"
      className={cn(
        "relative flex min-h-9 cursor-default items-center gap-3 py-2 pl-9 pr-3 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        className,
      )}
      checked={checked}
      {...props}
    >
      <span className="pointer-events-none absolute left-3 flex size-3.5 items-center justify-center text-current">
        <MenubarPrimitive.ItemIndicator>
          <CheckIcon className="size-3" />
        </MenubarPrimitive.ItemIndicator>
      </span>
      {children}
    </MenubarPrimitive.CheckboxItem>
  );
}

function MenubarRadioItem({
  className,
  children,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.RadioItem>) {
  return (
    <MenubarPrimitive.RadioItem
      data-slot="menubar-radio-item"
      className={cn(
        "relative flex min-h-9 cursor-default items-center gap-3 py-2 pl-9 pr-3 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-50",
        className,
      )}
      {...props}
    >
      <span className="pointer-events-none absolute left-3 flex size-3.5 items-center justify-center text-current">
        <MenubarPrimitive.ItemIndicator>
          <CircleIcon className="size-2 fill-current" />
        </MenubarPrimitive.ItemIndicator>
      </span>
      {children}
    </MenubarPrimitive.RadioItem>
  );
}

function MenubarLabel({
  className,
  inset,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Label> & {
  inset?: boolean;
}) {
  return (
    <MenubarPrimitive.Label
      data-slot="menubar-label"
      data-inset={inset}
      className={cn(
        "px-3 py-1.5 text-muted-foreground/60",
        omniMonoText.compact,
        "data-[inset]:pl-8",
        className,
      )}
      {...props}
    />
  );
}

function MenubarSeparator({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.Separator>) {
  return (
    <MenubarPrimitive.Separator
      data-slot="menubar-separator"
      className={cn("-mx-1 my-1 h-px bg-border/60", className)}
      {...props}
    />
  );
}

function MenubarShortcut({ className, ...props }: React.ComponentProps<"span">) {
  return (
    <span
      data-slot="menubar-shortcut"
      className={cn("ml-auto text-muted-foreground/60", omniMonoText.base, className)}
      {...props}
    />
  );
}

function MenubarSub({ ...props }: React.ComponentProps<typeof MenubarPrimitive.Sub>) {
  return <MenubarPrimitive.Sub data-slot="menubar-sub" {...props} />;
}

function MenubarSubTrigger({
  className,
  inset,
  children,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.SubTrigger> & {
  inset?: boolean;
}) {
  return (
    <MenubarPrimitive.SubTrigger
      data-slot="menubar-sub-trigger"
      data-inset={inset}
      className={cn(
        "flex min-h-9 cursor-default items-center gap-3 px-3 py-2 text-muted-foreground/90 outline-none transition-[color,background]",
        omniMonoText.menu,
        "hover:bg-muted/60 hover:text-foreground data-[highlighted]:bg-muted/60 data-[highlighted]:text-foreground",
        "focus-visible:ring-ring/40 focus-visible:ring-2",
        "data-[state=open]:bg-muted/60 data-[state=open]:text-foreground",
        "data-[inset]:pl-8",
        className,
      )}
      {...props}
    >
      {children}
      <ChevronRightIcon className="ml-auto size-3" />
    </MenubarPrimitive.SubTrigger>
  );
}

function MenubarSubContent({
  className,
  ...props
}: React.ComponentProps<typeof MenubarPrimitive.SubContent>) {
  return (
    <MenubarPrimitive.SubContent
      data-slot="menubar-sub-content"
      className={cn(
        "omni-glass-menu-surface z-50 min-w-[8rem] origin-(--radix-menubar-content-transform-origin) overflow-hidden p-1",
        "data-[state=open]:animate-in data-[state=open]:zoom-in-95 data-[state=open]:fade-in-0",
        "data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=closed]:fade-out-0",
        "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
        className,
      )}
      {...props}
    />
  );
}

export {
  Menubar,
  MenubarPortal,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarGroup,
  MenubarSeparator,
  MenubarLabel,
  MenubarItem,
  MenubarShortcut,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
};
