// registry/solid/ui/select.tsx
import {
  createContext,
  createEffect,
  createSignal,
  onCleanup,
  Show,
  splitProps,
  useContext,
  type Accessor,
  type ComponentProps,
  type JSX,
  type ParentProps,
} from "solid-js";
import * as SelectPrimitive from "@kobalte/core/select";
import { CheckIcon, ChevronDownIcon, ChevronUpIcon } from "lucide-solid";

import { glassSurfaceSubtleClass } from "@/registry/solid/lib/glass";
import { useOptionalFormControlProps } from "@/registry/solid/lib/form-control";
import { cn } from "@/registry/solid/lib/utils";

type SelectContentPosition = "popper" | "item-aligned";
type SelectContentAlign = "start" | "center" | "end";

type SelectLayoutContextValue = {
  align: Accessor<SelectContentAlign>;
  position: Accessor<SelectContentPosition>;
  setAlign: (align: SelectContentAlign) => void;
  setPosition: (position: SelectContentPosition) => void;
};

const SelectLayoutContext = createContext<SelectLayoutContextValue>();

function getPlacementFromAlign(align: SelectContentAlign) {
  switch (align) {
    case "start":
      return "bottom-start" as const;
    case "end":
      return "bottom-end" as const;
    default:
      return "bottom" as const;
  }
}

function Select<Option, OptGroup = never>(
  props: SelectPrimitive.SelectRootProps<Option, OptGroup> & { children?: JSX.Element },
) {
  const [local, rest] = splitProps(props, ["children", "placement", "sameWidth"]);
  const [position, setPosition] = createSignal<SelectContentPosition>("popper");
  const [align, setAlign] = createSignal<SelectContentAlign>("center");

  return (
    <SelectLayoutContext.Provider value={{ align, position, setAlign, setPosition }}>
      <SelectPrimitive.Root
        // Kobalte controls placement on the root, so content alignment is mirrored
        // through this local context to keep the public API close to the React variant.
        data-slot="select"
        placement={local.placement ?? getPlacementFromAlign(align())}
        sameWidth={local.sameWidth ?? position() === "popper"}
        {...rest}
      >
        {local.children}
      </SelectPrimitive.Root>
    </SelectLayoutContext.Provider>
  );
}

function SelectValue(
  props: Omit<ComponentProps<typeof SelectPrimitive.Value>, "children"> & {
    children?: JSX.Element | ((state: unknown) => JSX.Element);
  },
) {
  return (
    <SelectPrimitive.Value
      data-slot="select-value"
      {...(props as ComponentProps<typeof SelectPrimitive.Value>)}
    />
  );
}

function SelectTrigger(
  props: ComponentProps<typeof SelectPrimitive.Trigger> & {
    size?: "sm" | "default";
  },
) {
  const [local, rest] = splitProps(props, [
    "class",
    "children",
    "size",
    "id",
    "aria-describedby",
    "aria-invalid",
  ]);
  const formControlProps = useOptionalFormControlProps();
  const size = () => local.size ?? "default";
  return (
    <SelectPrimitive.Trigger
      data-slot="select-trigger"
      data-size={size()}
      id={local.id ?? formControlProps?.().id}
      aria-describedby={local["aria-describedby"] ?? formControlProps?.()["aria-describedby"]}
      aria-invalid={local["aria-invalid"] ?? formControlProps?.()["aria-invalid"]}
      class={cn(
        "flex w-fit items-center justify-between gap-2 px-3 py-2 text-sm whitespace-nowrap text-foreground/90 data-[placeholder]:text-muted-foreground/70 [&_svg:not([class*='text-'])]:text-muted-foreground/70 transition-[border,background,color,box-shadow] outline-none disabled:cursor-not-allowed disabled:opacity-50 data-[size=default]:h-10 data-[size=sm]:h-9",
        glassSurfaceSubtleClass,
        "focus-visible:border-foreground focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
        "aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive/30 dark:aria-invalid:focus-visible:ring-destructive/40",
        local.class,
      )}
      {...rest}
    >
      {local.children}
      <SelectPrimitive.Icon>
        <ChevronDownIcon class="size-4 opacity-50" />
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  );
}

function SelectContent(
  props: ComponentProps<typeof SelectPrimitive.Content> & {
    position?: "popper" | "item-aligned";
    align?: "start" | "center" | "end";
  },
) {
  const [local, rest] = splitProps(props, ["class", "children", "position", "align"]);
  const layout = useContext(SelectLayoutContext);
  const position = () => local.position ?? "popper";
  const align = () => local.align ?? "center";
  const [listboxRef, setListboxRef] = createSignal<HTMLElement>();
  const [canScrollUp, setCanScrollUp] = createSignal(false);
  const [canScrollDown, setCanScrollDown] = createSignal(false);

  const updateScrollButtons = () => {
    const listbox = listboxRef();
    if (!listbox) return;

    const hasOverflow = listbox.scrollHeight - listbox.clientHeight > 1;
    setCanScrollUp(hasOverflow && listbox.scrollTop > 1);
    setCanScrollDown(
      hasOverflow && listbox.scrollTop + listbox.clientHeight < listbox.scrollHeight - 1,
    );
  };

  createEffect(() => {
    layout?.setPosition(position());
    layout?.setAlign(align());
  });

  createEffect(() => {
    const listbox = listboxRef();
    if (!listbox) return;

    updateScrollButtons();

    const resizeObserver = new ResizeObserver(() => updateScrollButtons());
    resizeObserver.observe(listbox);
    listbox.addEventListener("scroll", updateScrollButtons, { passive: true });

    const frame = requestAnimationFrame(updateScrollButtons);

    onCleanup(() => {
      cancelAnimationFrame(frame);
      listbox.removeEventListener("scroll", updateScrollButtons);
      resizeObserver.disconnect();
    });
  });

  onCleanup(() => {
    layout?.setPosition("popper");
    layout?.setAlign("center");
  });

  return (
    <SelectPrimitive.Portal>
      <SelectPrimitive.Content
        data-slot="select-content"
        class={cn(
          "relative z-50 max-h-[var(--kb-popper-content-available-height)] min-w-[8rem] origin-[var(--kb-select-content-transform-origin)] overflow-x-hidden overflow-y-auto",
          glassSurfaceSubtleClass,
          "data-[expanded]:animate-in data-[closed]:animate-out data-[closed]:fade-out-0 data-[expanded]:fade-in-0 data-[closed]:zoom-out-95 data-[expanded]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
          position() === "popper" &&
            "data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1",
          local.class,
        )}
        {...rest}
      >
        <Show when={canScrollUp()}>
          <SelectScrollUpButton onClick={() => scrollSelectList(listboxRef(), "up")} />
        </Show>
        <SelectPrimitive.Listbox
          ref={setListboxRef}
          class={cn(
            "p-1",
            position() === "popper" && "w-full min-w-[var(--kb-select-trigger-width)] scroll-my-1",
          )}
        >
          {local.children}
        </SelectPrimitive.Listbox>
        <Show when={canScrollDown()}>
          <SelectScrollDownButton onClick={() => scrollSelectList(listboxRef(), "down")} />
        </Show>
      </SelectPrimitive.Content>
    </SelectPrimitive.Portal>
  );
}

function SelectGroup(props: ComponentProps<typeof SelectPrimitive.Section>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <SelectPrimitive.Section data-slot="select-group" class={local.class} {...rest}>
      {local.children}
    </SelectPrimitive.Section>
  );
}

function SelectLabel(props: ParentProps<{ class?: string } & JSX.HTMLAttributes<HTMLDivElement>>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="select-label"
      class={cn(
        "px-3 py-2 font-mono text-[10px] uppercase tracking-[0.28em] text-muted-foreground/90",
        local.class,
      )}
      {...rest}
    />
  );
}

function scrollSelectList(target: EventTarget | null, direction: "up" | "down") {
  if (!(target instanceof HTMLElement)) return;
  target.scrollBy({
    top: direction === "up" ? -40 : 40,
  });
}

function SelectItem(props: ComponentProps<typeof SelectPrimitive.Item>) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <SelectPrimitive.Item
      data-slot="select-item"
      class={cn(
        "relative flex w-full cursor-default items-center gap-3 px-3 py-2 text-[11px] font-mono uppercase tracking-[0.28em] text-muted-foreground/90 outline-hidden select-none transition-[background,color]",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-40",
        "hover:bg-foreground hover:text-background",
        "data-[highlighted]:bg-foreground data-[highlighted]:text-background",
        "data-[selected]:bg-foreground data-[selected]:text-background",
        "rounded-none",
        local.class,
      )}
      {...rest}
    >
      <span class="absolute right-2 flex size-3.5 items-center justify-center">
        <SelectPrimitive.ItemIndicator>
          <CheckIcon class="size-4" />
        </SelectPrimitive.ItemIndicator>
      </span>
      <SelectPrimitive.ItemLabel>{local.children}</SelectPrimitive.ItemLabel>
    </SelectPrimitive.Item>
  );
}

function SelectSeparator(
  props: ParentProps<{ class?: string } & JSX.HTMLAttributes<HTMLDivElement>>,
) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <div
      data-slot="select-separator"
      role="separator"
      class={cn(
        "pointer-events-none -mx-1 my-1 h-px bg-gradient-to-r from-transparent via-border/60 to-transparent",
        local.class,
      )}
      {...rest}
    />
  );
}

function SelectScrollUpButton(
  props: ParentProps<{ class?: string } & JSX.HTMLAttributes<HTMLDivElement>>,
) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div
      data-slot="select-scroll-up-button"
      class={cn("flex cursor-default items-center justify-center py-1", local.class)}
      onMouseDown={(event: MouseEvent) => event.preventDefault()}
      {...rest}
    >
      {local.children ?? <ChevronUpIcon class="size-4" />}
    </div>
  );
}

function SelectScrollDownButton(
  props: ParentProps<{ class?: string } & JSX.HTMLAttributes<HTMLDivElement>>,
) {
  const [local, rest] = splitProps(props, ["class", "children"]);
  return (
    <div
      data-slot="select-scroll-down-button"
      class={cn("flex cursor-default items-center justify-center py-1", local.class)}
      onMouseDown={(event: MouseEvent) => event.preventDefault()}
      {...rest}
    >
      {local.children ?? <ChevronDownIcon class="size-4" />}
    </div>
  );
}

export {
  Select,
  SelectContent,
  SelectGroup,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  SelectItem,
};

// registry/react/ui/select.tsx
"use client";

import * as React from "react";
import * as SelectPrimitive from "@radix-ui/react-select";
import { CheckIcon, ChevronDownIcon, ChevronUpIcon } from "lucide-react";

import { glassSurfaceSubtleClass } from "@/registry/react/lib/glass";
import { cn } from "@/registry/react/lib/utils";

function Select({ ...props }: React.ComponentProps<typeof SelectPrimitive.Root>) {
  return <SelectPrimitive.Root data-slot="select" {...props} />;
}

function SelectGroup({ ...props }: React.ComponentProps<typeof SelectPrimitive.Group>) {
  return <SelectPrimitive.Group data-slot="select-group" {...props} />;
}

function SelectValue({ ...props }: React.ComponentProps<typeof SelectPrimitive.Value>) {
  return <SelectPrimitive.Value data-slot="select-value" {...props} />;
}

function SelectTrigger({
  className,
  size = "default",
  children,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Trigger> & {
  size?: "sm" | "default";
}) {
  return (
    <SelectPrimitive.Trigger
      data-slot="select-trigger"
      data-size={size}
      className={cn(
        "flex w-fit items-center justify-between gap-2 px-3 py-2 text-sm whitespace-nowrap text-foreground/90 data-[placeholder]:text-muted-foreground/70 [&_svg:not([class*='text-'])]:text-muted-foreground/70 transition-[border,background,color,box-shadow] outline-none disabled:cursor-not-allowed disabled:opacity-50 data-[size=default]:h-10 data-[size=sm]:h-9",
        glassSurfaceSubtleClass,
        "focus-visible:border-foreground focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
        "aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive/30 dark:aria-invalid:focus-visible:ring-destructive/40",
        className,
      )}
      {...props}
    >
      {children}
      <SelectPrimitive.Icon asChild>
        <ChevronDownIcon className="size-4 opacity-50" />
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  );
}

function SelectContent({
  className,
  children,
  position = "popper",
  align = "center",
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Content>) {
  return (
    <SelectPrimitive.Portal>
      <SelectPrimitive.Content
        data-slot="select-content"
        className={cn(
          "relative z-50 max-h-(--radix-select-content-available-height) min-w-[8rem] origin-(--radix-select-content-transform-origin) overflow-x-hidden overflow-y-auto",
          glassSurfaceSubtleClass,
          "data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
          position === "popper" &&
            "data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1",
          className,
        )}
        position={position}
        align={align}
        {...props}
      >
        <SelectScrollUpButton />
        <SelectPrimitive.Viewport
          className={cn(
            "p-1",
            position === "popper" &&
              "h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)] scroll-my-1",
          )}
        >
          {children}
        </SelectPrimitive.Viewport>
        <SelectScrollDownButton />
      </SelectPrimitive.Content>
    </SelectPrimitive.Portal>
  );
}

function SelectLabel({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.Label>) {
  return (
    <SelectPrimitive.Label
      data-slot="select-label"
      className={cn(
        "px-3 py-2 font-mono text-[10px] uppercase tracking-[0.28em] text-muted-foreground/90",
        className,
      )}
      {...props}
    />
  );
}

function SelectItem({
  className,
  children,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Item>) {
  return (
    <SelectPrimitive.Item
      data-slot="select-item"
      className={cn(
        "relative flex w-full cursor-default items-center gap-3 px-3 py-2 text-[11px] font-mono uppercase tracking-[0.28em] text-muted-foreground/90 outline-hidden select-none transition-[background,color]",
        "data-[disabled]:pointer-events-none data-[disabled]:opacity-40",
        "hover:bg-foreground hover:text-background",
        "data-[state=checked]:bg-foreground data-[state=checked]:text-background",
        "rounded-none",
        className,
      )}
      {...props}
    >
      <span className="absolute right-2 flex size-3.5 items-center justify-center">
        <SelectPrimitive.ItemIndicator>
          <CheckIcon className="size-4" />
        </SelectPrimitive.ItemIndicator>
      </span>
      <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
    </SelectPrimitive.Item>
  );
}

function SelectSeparator({
  className,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.Separator>) {
  return (
    <SelectPrimitive.Separator
      data-slot="select-separator"
      className={cn(
        "pointer-events-none -mx-1 my-1 h-px bg-gradient-to-r from-transparent via-border/60 to-transparent",
        className,
      )}
      {...props}
    />
  );
}

function SelectScrollUpButton({
  className,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.ScrollUpButton>) {
  return (
    <SelectPrimitive.ScrollUpButton
      data-slot="select-scroll-up-button"
      className={cn("flex cursor-default items-center justify-center py-1", className)}
      {...props}
    >
      <ChevronUpIcon className="size-4" />
    </SelectPrimitive.ScrollUpButton>
  );
}

function SelectScrollDownButton({
  className,
  ...props
}: React.ComponentProps<typeof SelectPrimitive.ScrollDownButton>) {
  return (
    <SelectPrimitive.ScrollDownButton
      data-slot="select-scroll-down-button"
      className={cn("flex cursor-default items-center justify-center py-1", className)}
      {...props}
    >
      <ChevronDownIcon className="size-4" />
    </SelectPrimitive.ScrollDownButton>
  );
}

export {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
};
