// registry/solid/ui/spinner.tsx
import { type JSX, splitProps } from "solid-js";
import { Loader2Icon } from "lucide-solid";

import { cn } from "@/registry/solid/lib/utils";

function Spinner(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  const [local, rest] = splitProps(props, ["class"]);
  return (
    <Loader2Icon
      role="status"
      aria-label="Loading"
      data-slot="spinner"
      class={cn(
        "size-4 animate-spin text-foreground/80 drop-shadow-[var(--glass-drop-shadow-subtle)]",
        "dark:text-foreground",
        local.class,
      )}
      {...rest}
    />
  );
}

export { Spinner };

// registry/react/ui/spinner.tsx
import { Loader2Icon } from "lucide-react";

import { cn } from "@/registry/react/lib/utils";

function Spinner({ className, ...props }: React.ComponentProps<"svg">) {
  return (
    <Loader2Icon
      role="status"
      aria-label="Loading"
      data-slot="spinner"
      className={cn(
        "size-4 animate-spin text-foreground/80 drop-shadow-[var(--glass-drop-shadow-subtle)]",
        "dark:text-foreground",
        className,
      )}
      {...props}
    />
  );
}

export { Spinner };
