// apps/demo/src/components/solid-demo-map.tsx
import { Show, type Component, lazy } from "solid-js";

const demos: Record<string, Component> = {
  accordion: lazy(() => import("../demos/solid/accordion")),
  alert: lazy(() => import("../demos/solid/alert")),
  "alert-dialog": lazy(() => import("../demos/solid/alert-dialog")),
  "aspect-ratio": lazy(() => import("../demos/solid/aspect-ratio")),
  avatar: lazy(() => import("../demos/solid/avatar")),
  badge: lazy(() => import("../demos/solid/badge")),
  breadcrumb: lazy(() => import("../demos/solid/breadcrumb")),
  button: lazy(() => import("../demos/solid/button")),
  "button-group": lazy(() => import("../demos/solid/button-group")),
  calendar: lazy(() => import("../demos/solid/calendar")),
  card: lazy(() => import("../demos/solid/card")),
  carousel: lazy(() => import("../demos/solid/carousel")),
  chart: lazy(() => import("../demos/solid/chart")),
  checkbox: lazy(() => import("../demos/solid/checkbox")),
  collapsible: lazy(() => import("../demos/solid/collapsible")),
  combobox: lazy(() => import("../demos/solid/combobox")),
  command: lazy(() => import("../demos/solid/command")),
  "context-menu": lazy(() => import("../demos/solid/context-menu")),
  "data-table": lazy(() => import("../demos/solid/data-table")),
  "date-picker": lazy(() => import("../demos/solid/date-picker")),
  dialog: lazy(() => import("../demos/solid/dialog")),
  drawer: lazy(() => import("../demos/solid/drawer")),
  "dropdown-menu": lazy(() => import("../demos/solid/dropdown-menu")),
  empty: lazy(() => import("../demos/solid/empty")),
  field: lazy(() => import("../demos/solid/field")),
  form: lazy(() => import("../demos/solid/form")),
  "hover-card": lazy(() => import("../demos/solid/hover-card")),
  input: lazy(() => import("../demos/solid/input")),
  "input-group": lazy(() => import("../demos/solid/input-group")),
  "input-otp": lazy(() => import("../demos/solid/input-otp")),
  item: lazy(() => import("../demos/solid/item")),
  kbd: lazy(() => import("../demos/solid/kbd")),
  label: lazy(() => import("../demos/solid/label")),
  menubar: lazy(() => import("../demos/solid/menubar")),
  "navigation-menu": lazy(() => import("../demos/solid/navigation-menu")),
  pagination: lazy(() => import("../demos/solid/pagination")),
  popover: lazy(() => import("../demos/solid/popover")),
  progress: lazy(() => import("../demos/solid/progress")),
  "radio-group": lazy(() => import("../demos/solid/radio-group")),
  resizable: lazy(() => import("../demos/solid/resizable")),
  "scroll-area": lazy(() => import("../demos/solid/scroll-area")),
  select: lazy(() => import("../demos/solid/select")),
  separator: lazy(() => import("../demos/solid/separator")),
  sheet: lazy(() => import("../demos/solid/sheet")),
  skeleton: lazy(() => import("../demos/solid/skeleton")),
  slider: lazy(() => import("../demos/solid/slider")),
  sonner: lazy(() => import("../demos/solid/sonner")),
  spinner: lazy(() => import("../demos/solid/spinner")),
  switch: lazy(() => import("../demos/solid/switch")),
  table: lazy(() => import("../demos/solid/table")),
  tabs: lazy(() => import("../demos/solid/tabs")),
  textarea: lazy(() => import("../demos/solid/textarea")),
  toggle: lazy(() => import("../demos/solid/toggle")),
  "toggle-group": lazy(() => import("../demos/solid/toggle-group")),
  tooltip: lazy(() => import("../demos/solid/tooltip")),
  typography: lazy(() => import("../demos/solid/typography")),
  sidebar: lazy(() => import("../demos/solid/sidebar")),
  toast: lazy(() => import("../demos/solid/toast")),
  "react-hook-form": lazy(() => import("../demos/solid/react-hook-form")),
};

export default function SolidDemoRenderer(props: { name: string }) {
  const Demo = demos[props.name];
  return (
    <Show when={Demo} fallback={<p class="text-muted-foreground">Demo not available.</p>}>
      {Demo && <Demo />}
    </Show>
  );
}

// apps/demo/src/components/react-demo-map.tsx
import AccordionDemo from "../demos/react/accordion";
import AlertDemo from "../demos/react/alert";
import AlertDialogDemo from "../demos/react/alert-dialog";
import AspectRatioDemo from "../demos/react/aspect-ratio";
import AvatarDemo from "../demos/react/avatar";
import BadgeDemo from "../demos/react/badge";
import BreadcrumbDemo from "../demos/react/breadcrumb";
import ButtonDemo from "../demos/react/button";
import ButtonGroupDemo from "../demos/react/button-group";
import CalendarDemo from "../demos/react/calendar";
import CardDemo from "../demos/react/card";
import CarouselDemo from "../demos/react/carousel";
import ChartDemo from "../demos/react/chart";
import CheckboxDemo from "../demos/react/checkbox";
import CollapsibleDemo from "../demos/react/collapsible";
import ComboboxDemo from "../demos/react/combobox";
import CommandDemo from "../demos/react/command";
import ContextMenuDemo from "../demos/react/context-menu";
import DataTableDemo from "../demos/react/data-table";
import DatePickerDemo from "../demos/react/date-picker";
import DialogDemo from "../demos/react/dialog";
import DrawerDemo from "../demos/react/drawer";
import DropdownMenuDemo from "../demos/react/dropdown-menu";
import EmptyDemo from "../demos/react/empty";
import FieldDemo from "../demos/react/field";
import FormDemo from "../demos/react/form";
import HoverCardDemo from "../demos/react/hover-card";
import InputDemo from "../demos/react/input";
import InputGroupDemo from "../demos/react/input-group";
import InputOtpDemo from "../demos/react/input-otp";
import ItemDemo from "../demos/react/item";
import KbdDemo from "../demos/react/kbd";
import LabelDemo from "../demos/react/label";
import MenubarDemo from "../demos/react/menubar";
import NavigationMenuDemo from "../demos/react/navigation-menu";
import PaginationDemo from "../demos/react/pagination";
import PopoverDemo from "../demos/react/popover";
import ProgressDemo from "../demos/react/progress";
import RadioGroupDemo from "../demos/react/radio-group";
import ResizableDemo from "../demos/react/resizable";
import ScrollAreaDemo from "../demos/react/scroll-area";
import SelectDemo from "../demos/react/select";
import SeparatorDemo from "../demos/react/separator";
import SheetDemo from "../demos/react/sheet";
import SkeletonDemo from "../demos/react/skeleton";
import SliderDemo from "../demos/react/slider";
import SonnerDemo from "../demos/react/sonner";
import SpinnerDemo from "../demos/react/spinner";
import SwitchDemo from "../demos/react/switch";
import TableDemo from "../demos/react/table";
import TabsDemo from "../demos/react/tabs";
import TextareaDemo from "../demos/react/textarea";
import ToggleDemo from "../demos/react/toggle";
import ToggleGroupDemo from "../demos/react/toggle-group";
import TooltipDemo from "../demos/react/tooltip";
import TypographyDemo from "../demos/react/typography";
import SidebarDemo from "../demos/react/sidebar";
import ToastDemo from "../demos/react/toast";
import ReactHookFormDemo from "../demos/react/react-hook-form";

const demos: Record<string, React.ComponentType> = {
  accordion: AccordionDemo,
  alert: AlertDemo,
  "alert-dialog": AlertDialogDemo,
  "aspect-ratio": AspectRatioDemo,
  avatar: AvatarDemo,
  badge: BadgeDemo,
  breadcrumb: BreadcrumbDemo,
  button: ButtonDemo,
  "button-group": ButtonGroupDemo,
  calendar: CalendarDemo,
  card: CardDemo,
  carousel: CarouselDemo,
  chart: ChartDemo,
  checkbox: CheckboxDemo,
  collapsible: CollapsibleDemo,
  combobox: ComboboxDemo,
  command: CommandDemo,
  "context-menu": ContextMenuDemo,
  "data-table": DataTableDemo,
  "date-picker": DatePickerDemo,
  dialog: DialogDemo,
  drawer: DrawerDemo,
  "dropdown-menu": DropdownMenuDemo,
  empty: EmptyDemo,
  field: FieldDemo,
  form: FormDemo,
  "hover-card": HoverCardDemo,
  input: InputDemo,
  "input-group": InputGroupDemo,
  "input-otp": InputOtpDemo,
  item: ItemDemo,
  kbd: KbdDemo,
  label: LabelDemo,
  menubar: MenubarDemo,
  "navigation-menu": NavigationMenuDemo,
  pagination: PaginationDemo,
  popover: PopoverDemo,
  progress: ProgressDemo,
  "radio-group": RadioGroupDemo,
  resizable: ResizableDemo,
  "scroll-area": ScrollAreaDemo,
  select: SelectDemo,
  separator: SeparatorDemo,
  sheet: SheetDemo,
  skeleton: SkeletonDemo,
  slider: SliderDemo,
  sonner: SonnerDemo,
  spinner: SpinnerDemo,
  switch: SwitchDemo,
  table: TableDemo,
  tabs: TabsDemo,
  textarea: TextareaDemo,
  toggle: ToggleDemo,
  "toggle-group": ToggleGroupDemo,
  tooltip: TooltipDemo,
  typography: TypographyDemo,
  sidebar: SidebarDemo,
  toast: ToastDemo,
  "react-hook-form": ReactHookFormDemo,
};

export default function ReactDemoRenderer({ name }: { name: string }) {
  const Demo = demos[name];
  if (!Demo) return <p className="text-muted-foreground">Demo not available.</p>;
  return <Demo />;
}
